repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "pytest"
        language: system
        pass_filenames: false
