[tool.poetry]
name = "swing-trade-b3"
version = "0.1.0"
description = "Automatiza operações de Swing Trade na B3"
authors = ["Contributors <email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
prometheus-client = "^0.20.0"
psutil = "^5.9.0"
uvicorn = "^0.30.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
