name: Branch name

on:
  workflow_run:
    workflows: ["Auto rename Codex branches"]
    types:
      - completed

jobs:
  branch-name:
    name: Validate branch name
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          branch="${{ github.event.workflow_run.head_branch }}"
          if [[ ! "$branch" =~ ^(feat|fix|docs)/ ]]; then
            echo "Invalid branch name: $branch"
            echo "Branch names must start with 'feat/', 'fix/', or 'docs/'."
            echo "Rename your branch to use one of the allowed prefixes, e.g., 'fix/my-change'."
            exit 1
          fi
