name: Rename Codex Branch

on:
  pull_request:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  rename:
    name: Rename Codex branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request ? context.payload.pull_request.head.ref : context.ref.replace('refs/heads/', '');
            if (!/^(feat|fix|docs)\//.test(branch)) {
              const newBranch = `docs/${branch}`;
              await github.rest.repos.renameBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
                new_name: newBranch,
              });
              core.notice(`Branch renamed from ${branch} to ${newBranch}`);
            } else {
              core.notice(`Branch already complies with naming rule: ${branch}`);
            }
